### PR TITLE
Update MacOS compile process

### PR DESCRIPTION
**Pull request by Chengcheng-Xiao**
In this Pull request:
(1) Updated README.MacOS for MacOS v10.14.4 "Mojave"
(2) Addressed #8 [modified Patch file`MacOS.patch`]
(3) Addressed #9 [Add modified brew formula as `brew_pygtk.rb`]

### CODE REVIEW

**Comment by shekar2055** [comment]
Hi, While trying to install p4vasp on Catalina (following README.MacOS). I am getting following error. Can anyone help with this issue.

Thanks!
----------------------

cat vinfo.py >> lib/p4vasp/config.py
-------
cd install && python makeappletlist.py
cd odpdom && /Applications/Xcode.app/Contents/Developer/usr/bin/make libODP.a
make[1]: `libODP.a' is up to date.
cd src && /Applications/Xcode.app/Contents/Developer/usr/bin/make
g++-7 -L/usr/local/opt/libxml2/lib -shared -L. -o _cp4vasp.so cp4vasp_wrap.o -lp4vasp -L../odpdom -lODP `python2 fltk-config.py --use-gl --ldstaticflags` -lpthread `python-config --ldflags`
Undefined symbols for architecture x86_64:
  "_objc_opt_class", referenced from:
      -[FLWindow recursivelySendToSubwindows:] in libfltk.a(Fl_cocoa.o)
      rect_to_NSBitmapImageRep(Fl_Window*, int, int, int, int) in libfltk.a(Fl_cocoa.o)
      -[FLAppDelegate applicationDidChangeScreenParameters:] in libfltk.a(Fl_cocoa.o)
      +[FLApplication sendEvent:] in libfltk.a(Fl_cocoa.o)
      -[FLView insertText:replacementRange:] in libfltk.a(Fl_cocoa.o)
      -[FLView setMarkedText:selectedRange:replacementRange:] in libfltk.a(Fl_cocoa.o)
  "_objc_opt_isKindOfClass", referenced from:
      -[FLWindow recursivelySendToSubwindows:] in libfltk.a(Fl_cocoa.o)
      rect_to_NSBitmapImageRep(Fl_Window*, int, int, int, int) in libfltk.a(Fl_cocoa.o)
      -[FLAppDelegate applicationDidChangeScreenParameters:] in libfltk.a(Fl_cocoa.o)
      +[FLApplication sendEvent:] in libfltk.a(Fl_cocoa.o)
      -[FLView insertText:replacementRange:] in libfltk.a(Fl_cocoa.o)
      -[FLView setMarkedText:selectedRange:replacementRange:] in libfltk.a(Fl_cocoa.o)
  "_objc_opt_self", referenced from:
      +[FLWindowDelegate initialize] in libfltk.a(Fl_cocoa.o)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[1]: *** [_cp4vasp.so] Error 1
make: *** [p4vasp] Error 2

**Comment by Chengcheng-Xiao** [comment]
@shekar2055 After some light googling, I can only say that this problem has some thing to do with MacOS 10.15's objective-C. Have you tried updating your FLTK to the newest version? 

If that doesn't work, I would suggest you to either downgrade to 10.14 or choose alternatives.

Sorry I could not be more help on this matter. Personally, I'll stick with 10.14 since 10.15 dropped support for 32-bit apps.

**Comment by Chengcheng-Xiao** [comment]
Closed due to incompatibility with MacOS 10.15 and lack of support for f-orbital projection in VASP 5.4.4.

**Comment by rijal1370** [comment]
Does "$ brew install --build-from-source ./brew_pygtk.rb —-with-libglade " still work? because I am getting such error:
Updating Homebrew...
Error: No available formula with the name "./brew_pygtk.rb" 
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.

**Pull request closed without merging**
